/* ============================================================
   ERICSSON NETWORK SITES - script.js
   One script for every page. Each page says which part to run with
   <body data-page="...">:
     index.html     dash      dashboard (global overview)
     sites.html     sites     all sites, with filters and pages of 100
     critical.html  crit      all critical sites (80-100% load)
     site.html      site      details of one site (?id=...)
     history.html   history   list of imports
     import.html    import    daily overview of one import (?t=...)
   Order of this file:
     1. Data and helpers      4. Dashboard / daily overview
     2. Import history        5. Site page, sites list, history page
     3. Which data to show    6. Import window, search window, start
   The data is demo data (generated by gen). Nothing is sent anywhere.
   ============================================================ */

/* WL = the wilayas used in the demo data: [site code prefix, wilaya name].
   The prefix is the start of every site ID (ALG-0001 is a site of Algiers). */
const WL = [["ALG", "Algiers"], ["ORN", "Oran"], ["CON", "Constantine"], ["BLI", "Blida"], ["SET", "Sétif"], ["TIZ", "Tizi Ouzou"], ["ANN", "Annaba"], ["BAT", "Batna"], ["BEJ", "Béjaïa"], ["TLM", "Tlemcen"], ["MOS", "Mostaganem"], ["GHA", "Ghardaïa"]];

/* Small seeded random number generator. The same seed always gives the same
   sites, so every page shows the same data without any server or database. */
let seed = 7;
const rnd = () => {
  seed = (seed*16807)%2147483647;
  return seed/2147483647
};

/* Month names used when a date is written ("1 Oct 2026"). */
const MO = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/* fmt(date) -> "1 Oct 2026 · 09:15" (day, month, year, hour). */
const fmt = d => `${d.getDate()} ${MO[d.getMonth()]} ${d.getFullYear()} · ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;

/* iso(date) -> "2026-10-01", the format of the date filter field. */
const iso = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

/* cond(percent) -> status of a site from its load, using the project thresholds:
   0-50% good (green), 50-80% medium (orange), 80-100% critical (red). */
const cond = p => p >= 80 ? "crit" : p >= 50 ? "med" : "good";

/* LBL = the text shown for each status. */
const LBL = {
  crit: "Critical",
  med: "Medium",
  good: "Good",
  down: "Not working"
};

/* condS(site) -> same as cond(), but a site that is not working is always "down" (grey). */
const condS = s => s.down ? "down" : cond(s.load);

/* gen(seed) -> builds the list of 1,500 demo sites.
   Each site has: id, wilaya, load (%), last update (d), NE type (ne), entity type (et),
   measure point (mp), failure cause (fc, only if not working) and the load of the
   last 7 days (h). About 17% of the sites are "not working".
   To use real data later, replace this function with the code that reads the imported file. */
function gen(sd) {
  seed = sd;
  const S = [];
  for (let i = 0; i<1500; i++) {
    const w = WL[i%12];
    const d = new Date(2026, 8, 30-Math.floor(rnd()*4), Math.floor(rnd()*24), Math.floor(rnd()*12)*5);
    S.push({
      id: `${w[0]}-${String(Math.floor(i/12)+1).padStart(4,"0")}`,
      w: w[1],
      load: 1+Math.floor(rnd()*99),
      down: rnd()<.173,
      d,
      ne: rnd()>.5 ? "eNodeB" : "gNodeB",
      et: ["Cell", "Sector", "Carrier"][Math.floor(rnd()*3)],
      mp: rnd()>.5 ? "PRB utilization" : "Traffic load",
      tech: rnd()>.5 ? "4G + 5G" : "4G",
      cells: 3+Math.floor(rnd()*9),
      bw: [20, 40, 60, 100][Math.floor(rnd()*4)],
      pw: rnd()>.3 ? "Mains + battery" : "Mains + generator",
      bh: rnd()>.5 ? "Fiber" : "Microwave",
      yr: 2014+Math.floor(rnd()*11),
      up: (97+rnd()*2.9).toFixed(2),
      lat: (28+rnd()*8).toFixed(4),
      lng: (rnd()*8-1).toFixed(4),
      h: Array.from({
        length: 7
      }, () => 0)
    });
  }
  const FC = ["Power failure", "Backhaul link down", "Hardware fault", "Software crash"];
  S.forEach(s => {
    s.fc = s.down ? FC[Math.floor(rnd()*4)] : "";
    if (s.down)s.load = 0;
    let v = s.down ? 40 : s.load;
    s.h = s.h.map((_, k) => k === 6 ? s.load : (v = Math.min(99, Math.max(1, v+Math.round((rnd()-.5)*24)))))
  });
  return S
}

/* $(id) = short way to get an element of the page by its id. */
const $ = id => document.getElementById(id);

/* esc(text) = makes a text safe to show inside HTML (file names, failure reasons). */
const esc = t => t.replace(/[&<>"]/g, c =>({
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;"
}[c]));

/* Q = the parameters in the page address (?t=..., ?id=..., ?c=...).
   page = the name of the current page, read from <body data-page="...">. */
const Q = new URLSearchParams(location.search), page = document.body.dataset.page;

/* ---- Import history (kept in the browser) ---- */

/* Storage name of the import history inside the browser (localStorage). */
const HK = "ericsson_imports";

/* DEMO = two example imports shown the first time, so the History page is
   not empty. They stay in the list; new imports are added above them. */
const DEMO = [{
  n: "congestion_data.xlsx",
  t: new Date(2026, 9, 1, 9, 15).getTime(),
  s: 101,
  ok: true,
  c: 1500
}, {
  n: "congestion_data_2.xlsx",
  t: new Date(2026, 8, 30, 17, 40).getTime(),
  s: 202,
  ok: true,
  c: 1500
}];

/* HIST = the list of imports (newest first). It is loaded from the browser if saved. */
let HIST = DEMO;
try {
  const v = localStorage.getItem(HK);
  if (v)HIST = JSON.parse(v)
} catch (e) {}

/* addH(record) -> adds an import to the history and saves it in the browser.
   A record: n = file name, t = time (ms), s = data seed, ok = success, c = sites count, e = error. */
function addH(r) {
  HIST.unshift(r);
  try {
    localStorage.setItem(HK, JSON.stringify(HIST.slice(0, 200)))
  } catch (e) {}
}

/* ---- Data: ?t=<import time> opens that import, otherwise the global data ---- */

/* T = the import time in the address (?t=...). REC = that import, if it exists. */
const T = Q.get("t"), REC = T ? HIST.find(r => String(r.t) === T && r.ok) : null;

/* S = the list of sites used by the current page: the import's data when ?t= is
   in the address, otherwise the global data (seed 7). */
const S = gen(REC ? REC.s : 7);

/* cur = name and date of the data shown on this page. */
const cur = REC ? {
  name: REC.n,
  ts: new Date(REC.t)
}
: {
  name: "Sample data",
  ts: new Date()
};

/* tq = "?t=..." to add to links so that the next page keeps the same import. */
const tq = T ? "?t="+T : "";

/* dayL() -> the day of the current import, e.g. "1 Oct 2026". */
const dayL = () => fmt(cur.ts).split(" · ")[0];

/* ---- Dashboard / daily overview ---- */

/* ---- Daily overview ---- */

/* pct(a, b) -> a as a rounded percentage of b. */
const pct = (a, b) => Math.round(a/b*100);

/* donut(items, bigNumber, smallLabel) -> HTML of a donut chart.
   The ring is drawn with SVG circles: each item gets an arc, with a small gap
   between arcs. The legend (name + %) is written under the ring. */
const donut = (it, big, sm) => {
  const R = 77.4,
  C = 2*Math.PI*R,
  G = 4.6,
  tot = it.reduce((x, y) => x+y.v, 0) || 1;
  let a = 0;
  const arcs = it.map(y => {
    const L = y.v/tot*C,
    d = `<circle cx="90" cy="90" r="${R}" fill="none" stroke-width="25.2" style="stroke:${y.c}" stroke-dasharray="${Math.max(L-G,1)} ${C}" stroke-dashoffset="${-(a+G/2)}"/>`;
    a += L;
    return d
  }).join("");
  return `<div><div class="dn"><svg width="180" height="180" viewBox="0 0 180 180" style="transform:rotate(-90deg)">${arcs}</svg><span>${big}<small>${sm}</small></span></div><div class="lg">${it.map(y=>`<div><i style="background:${y.c}"></i>${y.l} ${pct(y.v,tot)}%</div>`).join("")}</div></div>`
};

/* cols(items, gap, barWidth, fontSize) -> HTML of a column chart.
   Each column = value on top, bar (height scaled to the highest value, max 170px), label. */
const cols = (it, g, bw, fs) => {
  const m = Math.max(...it.map(y => y.v), 1);
  return `<div class="cols" style="gap:${g}px;--bw:${bw}px">${it.map(y=>`<div style="font-size:${fs}px"><b>${y.v}</b><i style="height:${Math.max(16,Math.round(y.v/m*170))}px;background:${y.c}"></i>${y.l}</div>`).join("")}</div>`
};

/* dayView(prefix, sites) -> fills the dashboard cards.
   prefix "g" = global dashboard (index.html), prefix "d" = daily overview (import.html).
   It fills: availability card, "Sites by status" card, "Top 5 wilayas" card. */
function dayView(p = "d", D = S) {
  const sfx = p === "g" ? "global" : "this import",
  set = (id, t) => {
    const e = $(id);
    if (e)e.textContent = t
  };
  set(p+"day", dayL());
  set(p+"file", `${cur.name} · imported ${fmt(cur.ts)} · ${D.length.toLocaleString()} sites`);
  /* Split the sites: working / not working, count each condition, count critical sites per wilaya. */
  const W = D.filter(x => !x.down),
  n = W.length,
  dn = D.length-n,
  c = {
    crit: 0,
    med: 0,
    good: 0
  },
  wc = {},
  all = {};
  D.forEach(x => all[x.w] = (all[x.w] || 0)+1);
  W.forEach(x => {
    const k = cond(x.load);
    c[k]++;
    if (k === "crit")wc[x.w] = (wc[x.w] || 0)+1
  });
  const H = t => `<b style="font-size:18px">${t[0]}</b><p class="sub" style="font-size:13px">${t[1]}</p>`;
  /* Availability card: total, working, not working and the blue/grey bar. */
  $(p+"av").innerHTML = `<div><small class="mu">Total sites</small><b>${D.length.toLocaleString()}</b></div><div><small class="mu">Working</small><b>${n.toLocaleString()}</b><span style="color:var(--blue);font-weight:600;font-size:12px">${pct(n,D.length)}% operational</span></div><div><small class="mu">Not working</small><b>${dn.toLocaleString()}</b><span class="c-down" style="font-weight:600;font-size:12px">${pct(dn,D.length)}% down</span></div>`;
  $(p+"st").innerHTML = `<i style="width:${n/D.length*100}%;background:var(--blue)"></i><i style="flex:1;background:var(--down)"></i>`;
  /* "Sites by status" card: donut, columns and the breakdown tiles (critical / medium / good). */
  const cs = [{
    l: "Critical",
    v: c.crit,
    c: "var(--crit)"
  }, {
    l: "Medium",
    v: c.med,
    c: "var(--med)"
  }, {
    l: "Good",
    v: c.good,
    c: "var(--good)"
  }],
  R = ["80–100% load", "50–80% load", "0–50% load"];
  const tile = (y, r) => `<div class="tile"><i style="background:${y.c}"></i><div style="flex:1"><b>${y.l}</b><br><span class="mu" style="font-size:12px">${r}</span></div><div style="text-align:right"><b>${y.v.toLocaleString()} sites</b><br><span style="color:${y.c};font-size:12px">${pct(y.v,n)}% of network</span></div></div>`;
  $(p+"ss").innerHTML = H(["Sites by status", "Number & share of working sites · "+sfx])+`<div class="cc">${donut(cs,n.toLocaleString(),"sites")}${cols(cs,28,56,12)}<div class="dp"><small class="mu">BREAKDOWN</small>${cs.map((y,k)=>tile(y,R[k])).join("")}</div></div>`;
  /* "Top 5 wilayas" card: five wilayas with the most critical sites, one red shade each. */
  const SH = ["#b42318", "#e5352b", "#f04438", "#f97066", "#fda29b"];
  const top = Object.entries(wc).sort((a, b) => b[1]-a[1]).slice(0, 5).map((e, k) =>({
    l: e[0],
    v: e[1],
    c: SH[k]
  }));
  const rows = top.map(y => {
    const r = pct(y.v, all[y.l]);
    return `<div class="rw"><b>${y.l}</b><b class="c-crit">${y.v}</b><span class="mu">${all[y.l]}</span><span style="display:flex;align-items:center;gap:8px"><span class="track" style="min-width:0;flex:1"><i style="width:${Math.min(100,r*2.5)}%;background:${y.c}"></i></span><b>${r}%</b></span></div>`
  }).join("");
  $(p+"ww").innerHTML = H(["Top 5 wilayas · critical sites", "Wilayas with the most critical sites (80–100% load) · "+sfx])+`<div class="cc">${donut(top,top.reduce((a,y)=>a+y.v,0),"critical sites")}${cols(top,16,44,11)}<div class="dp"><small class="mu">CRITICAL RATE PER WILAYA</small><div><div class="rw h"><span>WILAYA</span><span>CRITICAL</span><span>TOTAL SITES</span><span>RATE</span></div>${rows}</div><small class="mu">Rate = critical sites ÷ total sites in the wilaya</small></div></div>`
}

/* ---- Dashboard lists ---- */

/* gLists(sites) -> the two lists under the dashboard cards: top 10 critical sites
   and bottom 10 near-empty sites (only working sites), with their buttons.
   Every row is clickable: the site ID is a link and a click on the row opens
   site.html?id=<site ID>&from=dash, the page with all the information of that site
   (from=dash makes its "back" links return to the dashboard). */
function gLists(D) {
  /* Split the sites: working / not working, count each condition, count critical sites per wilaya. */
  const W = D.filter(x => !x.down),
  hi = [...W].sort((a, b) => b.load-a.load).slice(0, 10),
  lo = [...W].sort((a, b) => a.load-b.load).slice(0, 10);
  const tb = (t, sub, col, a, btn, id) => `<b style="font-size:18px"><i style="display:inline-block;width:12px;height:12px;border-radius:50%;background:${col};margin-right:10px"></i>${t}</b><p class="sub" style="font-size:13px;margin:4px 0 12px">${sub}</p><div class="tw"><table style="min-width:420px"><thead><tr><th>#</th><th>SITE ID</th><th>WILAYA</th><th style="width:30%">LOAD</th><th class="r">%</th></tr></thead><tbody>${a.map((x,i)=>{const c=cond(x.load);return `<tr class="go" data-href="site.html?id=${x.id}&from=dash"><td class="mu">${i+1}</td><td class="b"><a class="sl" href="site.html?id=${x.id}&from=dash">${x.id}</a></td><td class="mu">${x.w}</td><td><div class="track"><i style="width:${x.load}%;background:var(--${c})"></i></div></td><td class="r b c-${c}">${x.load}%</td></tr>`}).join("")}</tbody></table></div><div style="margin-top:16px"><a class="btn" href="${id}">${btn} →</a></div>`;
  $("gtop").innerHTML = tb("Top 10 critical sites", "Highest load · 80–100% shown in red", "var(--crit)", hi, "View all critical sites", "critical.html");
  $("gbot").innerHTML = tb("Bottom 10 · near empty", "Lowest load · 0–50% shown in green", "var(--good)", lo, "View all near-empty sites", "sites.html?c=good&sort=asc");
  /* Click on a row (anywhere except the ID link, which already works) -> open that site's page. */
  [$("gtop"), $("gbot")].forEach(card => card.addEventListener("click", e => {
    const row = e.target.closest("tr[data-href]");
    if (row && !e.target.closest("a")) location.href = row.dataset.href
  }))
}

/* ---- Site page ---- */

/* renderSite(site) -> fills site.html: details, load summary, load graph, fixed report. */
function renderSite(s) {
  const c = condS(s);
  $("dcr").textContent = s.id;
  $("dt").textContent = s.id;
  $("ds").textContent = `${s.w} · ${LBL[c]}`;
  const K = [["Site ID", s.id], ["Wilaya", s.w], ["Condition", `<span class="c-${c}">${LBL[c]}</span>`], ["NE type", s.ne], ["Entity type", s.et], ["Measure point", s.mp], ["End time", fmt(s.d)]];
  if (s.fc)K.push(["Failure cause", s.fc]);
  $("dg").innerHTML = K.map(k => `<div class="k"><small>${k[0]}</small><b>${k[1]}</b></div>`).join("");
  const v = s.h.filter(x => x>0),
  f = n => v.length ? n+"%" : "—";
  $("dl").innerHTML = [["Average load", f(Math.round(v.reduce((a, b) => a+b, 0)/(v.length || 1)))], ["Maximum load", f(Math.max(...v))], ["Minimum load", f(Math.min(...v))]].map(k => `<div class="k"><small>${k[0]}</small><b>${k[1]}</b></div>`).join("");
  /* Load graph (SVG): width/height and margins, then the x (day) and y (percent) scales. */
  const GW = 700,
  GH = 260,
  GL = 44,
  GR = 20,
  GT = 20,
  GB = 36,
  X = i => GL+i*(GW-GL-GR)/6,
  Y = v => GT+(100-v)/100*(GH-GT-GB);
  const DL = s.h.map((x, i) => {
    const d = new Date(s.d);
    d.setDate(d.getDate()-(6-i));
    return `${d.getDate()} ${MO[d.getMonth()]}`
  });
  let gg = [0, 20, 40, 60, 80, 100].map(t => `<line x1="${GL}" x2="${GW-GR}" y1="${Y(t)}" y2="${Y(t)}" style="stroke:var(--bd)"/><text x="${GL-8}" y="${Y(t)+4}" text-anchor="end">${t}%</text>`).join("");
  gg += [[50, "med"], [80, "crit"]].map(([t, k]) => `<line x1="${GL}" x2="${GW-GR}" y1="${Y(t)}" y2="${Y(t)}" stroke-dasharray="4 4" style="stroke:var(--${k})"/>`).join("");
  const pts = s.h.map((x, i) => `${X(i)},${Y(x)}`).join(" ");
  const dots = s.h.map((x, i) => {
    const off = s.down && i === 6,
    k = off ? "down" : cond(x);
    return `<circle cx="${X(i)}" cy="${Y(x)}" r="5" style="fill:var(--${k});stroke:var(--bg);stroke-width:2"/><text x="${X(i)}" y="${Y(x)-11}" text-anchor="middle" style="fill:var(--tx);font-weight:600">${off?"Off":x+"%"}</text><text x="${X(i)}" y="${GH-12}" text-anchor="middle">${DL[i]}</text>`
  }).join("");
  $("dh").innerHTML = `<svg viewBox="0 0 ${GW} ${GH}" width="100%" role="img" aria-label="Load by day, in percent">${gg}<polyline points="${pts}" fill="none" style="stroke:var(--blue)" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>${dots}</svg>`;
  /* The fixed report: one text for each condition (critical, medium, good, not working). */
  const RP = {
    crit: "Critical load. This site is running at 80% or more of its capacity and is close to saturation, which can cause congestion and a poorer service for users. Recommended actions: review the recent traffic growth, plan a capacity upgrade or load balancing with neighboring sites, and follow this site daily until its load goes back below 80%.",
    med: "Medium load. This site is working normally (50–80% of its capacity) but has limited room left. Recommended actions: keep monitoring the load trend over the coming days and include the site in capacity planning if the load keeps rising.",
    good: "Good load. This site is below 50% of its capacity and has enough room for the current traffic. No action is needed; keep the routine monitoring.",
    down: "Site not working. This site is out of service and carries no traffic. Recommended actions: check the failure cause above, send a field team if needed, and restore the service as soon as possible. Neighboring sites may take extra traffic until it is back."
  };
  $("rp").textContent = LBL[c];
  $("rp").style.background = `var(--${c})`;
  $("rt").textContent = RP[c];
}

/* initSite() -> finds the site from ?id=... and shows it.
   The "back" links return to the list of the same import. */
function initSite() {
  const s = S.find(x => x.id === Q.get("id"));
  /* Opened from the dashboard lists (?from=dash): "back" goes to the dashboard.
     Otherwise "back" goes to the list of sites of the same import. */
  const fromDash = Q.get("from") === "dash";
  document.querySelectorAll("[data-back]").forEach(a => {
    a.href = fromDash ? "index.html" : "sites.html"+tq;
    a.textContent = fromDash ? a.textContent.replace("All sites", "Dashboard").replace("Back to all sites", "Back to dashboard") : a.textContent
  });
  if (!s) {
    $("dt").textContent = "Site not found";
    return
  }
  renderSite(s)
}

/* ---- Sites list (all sites, critical sites, sites of an import) ---- */

/* initList() -> everything on sites.html and critical.html:
   filters (site ID, wilaya, day, condition), sort by load, pages of 100 sites.
   On critical.html the condition is locked on "critical". */
function initList() {
  const crit = page === "crit";
  WL.forEach(w => $("fw").insertAdjacentHTML("beforeend", `<option>${w[1]}</option>`));
  /* State of the list: sort direction, current page, sites per page (100). */
  const st = {
    sort: "desc",
    page: 1
  },
  PER = 100;
  function list() {
    const id = $("fid").value.trim().toLowerCase(),
    w = $("fw").value,
    d = $("fd").value,
    c = $("fc").value;
    return S.filter(s =>(!id || s.id.toLowerCase().includes(id)) && (!w || s.w === w) && (!d || iso(s.d) === d) && (!c || condS(s) === c)).sort((a, b) =>(a.down-b.down) || (st.sort === "desc" ? b.load-a.load : a.load-b.load))
  }
  function render() {
    const L = list(),
    n = L.length,
    pages = Math.max(1, Math.ceil(n/PER));
    st.page = Math.min(st.page, pages);
    const a = (st.page-1)*PER,
    P = L.slice(a, a+PER);
    $("count").textContent = `${n.toLocaleString()} sites`;
    $("range").textContent = n ? `· showing ${a+1}–${a+P.length}` : "";
    $("empty").classList.toggle("hidden", n>0);
    $("rows").innerHTML = P.map((s, i) => {
      const c = condS(s);
      return `<tr><td class="mu">${a+i+1}</td><td class="b">${s.id}</td><td class="mu">${fmt(s.d)}</td><td>${s.w}</td><td><div class="track"><i style="width:${s.load}%;background:var(--${c})"></i></div></td><td class="r b c-${c}">${s.down?"—":s.load+"%"}</td><td class="r"><a class="more" href="site.html?id=${s.id}${T?"&t="+T:""}">More info</a></td></tr>`
    }).join("");
    let h = `<button ${st.page===1?"disabled":""} data-p="${st.page-1}" aria-label="Previous">‹</button>`;
    let last = 0;
    for (let p = 1; p <= pages; p++) {
      if (p === 1 || p === pages || Math.abs(p-st.page) <= 1) {
        if (p-last>1)h += `<button disabled>…</button>`;
        h += `<button class="${p===st.page?"on":""}" data-p="${p}">${p}</button>`;
        last = p
      }
    }
    h += `<button ${st.page===pages?"disabled":""} data-p="${st.page+1}" aria-label="Next">›</button>`;
    $("pg").innerHTML = n ? h : "";
  } ["fid", "fw", "fd", "fc"].forEach(i => $(i).addEventListener("input", () => {
    st.page = 1;
    render()
  }));
  $("sort").onclick = e => {
    const b = e.target.closest("button");
    if (!b)return;
    st.sort = b.dataset.s;
    [...$("sort").children].forEach(x => x.classList.toggle("on", x === b));
    st.page = 1;
    render()
  };
  $("reset").onclick = () => {
    ["fid", "fw", "fd"].forEach(i => $(i).value = "");
    if (!crit)$("fc").value = "";
    st.page = 1;
    render()
  };
  $("pg").onclick = e => {
    const b = e.target.closest("button");
    if (b && !b.disabled) {
      st.page = +b.dataset.p;
      render();
      $("count").scrollIntoView({
        block: "start"
      })
    }
  };
  [["fid", "id"], ["fw", "w"], ["fd", "d"], ["fc", "c"]].forEach(([i, k]) => {
    if (Q.get(k))$(i).value = Q.get(k)
  });
  if (crit) {
    $("fc").value = "crit";
    $("fc").disabled = true;
    $("lc").textContent = "Dashboard / Critical sites";
    $("lh").textContent = "Critical sites";
    $("ls").textContent = "Every critical site (80–100% load) in the global data. Sort or search to find a site."
  }
  if (REC) {
    $("lc").innerHTML = `<a href="import.html?t=${T}" style="color:inherit">Daily overview</a> / Sites from import`;
    $("lh").textContent = `Sites from import · ${dayL()}`;
    $("ls").textContent = `All ${S.length.toLocaleString()} sites in ${cur.name}. Filter, sort and open any site for details.`
  }
  st.sort = Q.get("sort") === "asc" ? "asc" : "desc";
  [...$("sort").children].forEach(x => x.classList.toggle("on", x.dataset.s === st.sort));
  render()
}

/* ---- History page ---- */

/* renderH() -> fills the History table (file, import date and hour, sites, status). */
function renderH() {
  $("hempty").classList.toggle("hidden", HIST.length>0);
  $("hrows").innerHTML = HIST.map((r, i) => `<tr><td class="mu">${HIST.length-i}</td><td class="b">${esc(r.n)}</td><td class="mu">${fmt(new Date(r.t))}</td><td>${r.ok?r.c.toLocaleString():"—"}</td><td>${r.ok?'<span class="pill" style="background:var(--good)">Successful</span>':`<span class="pill" style="background:var(--crit)">Failed</span><div class="mu" style="font-size:12px;margin-top:4px">${esc(r.e)}</div>`}</td><td class="r">${r.ok?`<a class="hv" href="import.html?t=${r.t}">View details</a>`:""}</td></tr>`).join("")
}

/* ---- Import window ---- */

/* The import window and the search window share one pop-up (#mod).
   mb = its content area. OKX = accepted file types. file = the selected file. */
const mod = $("mod"), mb = $("mbody"), OKX = /\.(csv|xlsx|xls)$/i;
let file = null;

/* closeM() / openM() = hide and show the pop-up window. */
function closeM() {
  mod.classList.add("hidden")
}
function openM() {
  mod.classList.remove("hidden");
  idle()
}

/* idle() = first screen of the import window: choose a file, then press Import. */
function idle() {
  file = null;
  mb.innerHTML = `<h2>Import data</h2><p>Select the file with today's site data.</p><label class="drop"><input id="mf" type="file" accept=".csv,.xlsx,.xls"><b>Select a file</b><span class="mu">CSV or Excel, up to 10 MB</span></label><div class="mu" id="fn">No file selected</div><div class="acts"><button class="btn" id="mc">Cancel</button><button class="btn p" id="mi" disabled>Import</button></div>`;
  $("mf").onchange = e => {
    file = e.target.files[0] || null;
    $("fn").textContent = file ? file.name : "No file selected";
    $("mi").disabled = !file
  };
  $("mc").onclick = closeM;
  $("mi").onclick = upload
}

/* upload() = second screen: a progress bar while the file is "imported". */
function upload() {
  mb.innerHTML = `<h2>Importing…</h2><p>${esc(file.name)}</p><div class="track" style="height:8px"><i id="pr" style="width:0;background:var(--blue)"></i></div>`;
  let p = 0;
  const t = setInterval(() => {
    p += 12+Math.random()*16;
    $("pr").style.width = Math.min(p, 100)+"%";
    if (p >= 100) {
      clearInterval(t);
      done()
    }
  }, 140)
}

/* done() = result screen. It checks the file (type, empty, size):
   - a problem -> "Import failed" with the reason, saved in the history;
   - no problem -> "Import successful", saved in the history, and the button
     "More details" opens import.html?t=<import time>.
   Note: this demo does not read the file content yet. */
function done() {
  /* Check the selected file: unsupported type, empty file, or larger than 10 MB. */
  const bad = !OKX.test(file.name) ? "This file type isn't supported. Use a CSV or Excel file (.csv, .xlsx, .xls)." : file.size === 0 ? "The file is empty. Select a file that contains site data." : file.size>10485760 ? "The file is larger than 10 MB. Split it and import again." : "";
  if (bad) {
    addH({
      n: file.name,
      t: Date.now(),
      ok: false,
      e: bad
    });
    if (page === "history")renderH();
    mb.innerHTML = `<div class="ic" style="background:var(--crit)">!</div><h2>Import failed</h2><p>${bad}</p><div class="acts"><button class="btn" id="mc">Cancel</button><button class="btn p" id="mr">Try again</button></div>`;
    $("mc").onclick = closeM;
    $("mr").onclick = idle;
    return
  }
  /* Success: save this import (its seed rebuilds the same data later) and show the success window. */
  const sd = 1+Math.floor(Math.random()*2147483000),
  ts = Date.now();
  addH({
    n: file.name,
    t: ts,
    s: sd,
    ok: true,
    c: 1500
  });
  if (page === "history")renderH();
  mb.innerHTML = `<div class="ic" style="background:var(--good)">✓</div><h2>Import successful</h2><p>${esc(file.name)} · 1,500 sites for ${fmt(new Date(ts)).split(" · ")[0]}</p><div class="acts"><button class="btn" id="mc">Close</button><button class="btn p" id="md">More details</button></div>`;
  $("mc").onclick = closeM;
  $("md").onclick = () => {
    location.href = "import.html?t="+ts
  }
}

/* ---- Search window ---- */

/* openSearch() = the search window (site ID, wilaya, date).
   Search opens sites.html with these filters in the address. */
function openSearch() {
  mod.classList.remove("hidden");
  mb.innerHTML = `<h2>Search sites</h2><label>Site ID<input id="sid" placeholder="e.g. ALG-0412"></label><label>Wilaya<select id="swl"><option value="">All wilayas</option>${WL.map(w=>`<option>${w[1]}</option>`).join("")}</select></label><label>Date<input id="sdt" type="date"></label><div class="acts"><button class="btn" id="sx">Clear</button><button class="btn p" id="sg">Search</button></div>`;
  $("sx").onclick = () =>["sid", "swl", "sdt"].forEach(i => $(i).value = "");
  $("sg").onclick = () => {
    const p = new URLSearchParams();
    [["sid", "id"], ["swl", "w"], ["sdt", "d"]].forEach(([i, k]) => {
      if ($(i).value)p.set(k, $(i).value)
    });
    location.href = "sites.html?"+p
  }
}

/* ---- Start ---- */

/* Buttons of the top bar and ways to close the window (outside click, Esc key). */
$("imp").onclick = openM;
$("sbar").onclick = openSearch;
mod.addEventListener("click", e => {
  if (e.target === mod)closeM()
});
document.addEventListener("keydown", e => {
  if (e.key === "Escape")closeM()
});

/* START: each page runs only its own part (page = <body data-page="...">). */
if (page === "dash") {
  dayView("g", S);
  gLists(S)
}
if (page === "import") {
  dayView("d", S);
  $("dall").href = "sites.html"+tq
}
if (page === "history")renderH();
if (page === "site")initSite();
if (page === "sites" || page === "crit")initList();